[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
terrafund = "HyE9YtQ2JDSpfqyWN1Z1y7jv4LH9Z7yAz98GvZ1kmY7f"

[programs.devnet]
terrafund = "HyE9YtQ2JDSpfqyWN1Z1y7jv4LH9Z7yAz98GvZ1kmY7f"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/subodh/keypair_cohorts.json"


[scripts]
test = "../node_modules/.bin/jest --preset ts-jest"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "127.0.0.1"
ledger = ".anchor/test-ledger"
rpc_port = 8899
